remote_theme: just-the-docs/just-the-docs

url: https://a.kbve.com

author:
  name: h0lybyte
color_scheme: dark

footer_content: true
footer_siderbar: true

discord_server_id:  342732838598082562

title: "KBVE Archive v1"


plugins:
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-mentions


jekyll-mentions:
  base_url: https://kbve.com/u

