remote_theme: just-the-docs/just-the-docs

url: https://kbve.com
baseurl: https://kbve.com

author:
  name: h0lybyte
color_scheme: dark

footer_content: true
footer_siderbar: true

discord_server_id:  342732838598082562

title: "KBVE Archive"


plugins:
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-mentions
  - jeql
  - premonition
  - jekyll-gzip
  - jekyll-redirect-from


jekyll-mentions:
  base_url: https://kbve.com/u

jeql:
  github:
    url: "https://api.github.com/graphql"